Add tabs in MainActivity
bperdija/Cell-Identifier pull request #7
Opened 2023-11-15 08:37 UTC by aerinpark

2023-11-15 22:59 UTC, bperdija requested changes

2023-11-15 22:59 UTC, bperdija commented on app/src/main/AndroidManifest.xml
See if we can default to light mode

2023-11-16 02:39 UTC, aerinpark commented on app/src/main/AndroidManifest.xml
Fixed. Now it's in light mode

2023-11-16 04:54 UTC, bperdija approved these changes
Looks great!!! Thank you! :)

2023-11-16 05:23 UTC, Jramacula approved these changes
Looks good! :+1:

2023-11-16 05:25 UTC, merged